package org.ivvy.cxf.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-06-07T18:13:04.968+08:00
 * Generated source version: 2.4.0
 * 
 */
 
@WebService(targetNamespace = "http://ws.ivvy.org/", name = "BankServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface BankServicePortType {

    @WebResult(name = "return", targetNamespace = "http://ws.ivvy.org/")
    @RequestWrapper(localName = "getBalance", targetNamespace = "http://ws.ivvy.org/", className = "org.ivvy.cxf.client.GetBalance")
    @WebMethod
    @ResponseWrapper(localName = "getBalanceResponse", targetNamespace = "http://ws.ivvy.org/", className = "org.ivvy.cxf.client.GetBalanceResponse")
    public java.lang.String getBalance(
        @WebParam(name = "arg0", targetNamespace = "http://ws.ivvy.org/")
        java.lang.String arg0
    );
}
