
package org.ivvy.ws.xfire;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "HelloWorldService", targetNamespace = "http://127.0.0.1:8080/service/helloWorld", wsdlLocation = "http://127.0.0.1:8080/WS030_XFire_Server/services/HelloWorldService?wsdl")
public class HelloWorldService
    extends Service
{

    private final static URL HELLOWORLDSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.ivvy.ws.xfire.HelloWorldService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.ivvy.ws.xfire.HelloWorldService.class.getResource(".");
            url = new URL(baseUrl, "http://127.0.0.1:8080/WS030_XFire_Server/services/HelloWorldService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://127.0.0.1:8080/WS030_XFire_Server/services/HelloWorldService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        HELLOWORLDSERVICE_WSDL_LOCATION = url;
    }

    public HelloWorldService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorldService() {
        super(HELLOWORLDSERVICE_WSDL_LOCATION, new QName("http://127.0.0.1:8080/service/helloWorld", "HelloWorldService"));
    }

    /**
     * 
     * @return
     *     returns HelloWorldServicePortType
     */
    @WebEndpoint(name = "HelloWorldServiceHttpPort")
    public HelloWorldServicePortType getHelloWorldServiceHttpPort() {
        return super.getPort(new QName("http://127.0.0.1:8080/service/helloWorld", "HelloWorldServiceHttpPort"), HelloWorldServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorldServicePortType
     */
    @WebEndpoint(name = "HelloWorldServiceHttpPort")
    public HelloWorldServicePortType getHelloWorldServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://127.0.0.1:8080/service/helloWorld", "HelloWorldServiceHttpPort"), HelloWorldServicePortType.class, features);
    }

}
